import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {ethers} from 'ethers';
import {hash} from '../adapters/remix.mjs';
export const SUPPORTED_VERSION='v0.8.30+commit.73712a01';
export const canonical=value=>JSON.stringify(sort(value));
function sort(x){if(Array.isArray(x))return x.map(sort);if(x&&typeof x==='object')return Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])]));return x;}
export function localCompile(input){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[fileURLToPath(new URL('./compiler-child.mjs',import.meta.url))],{stdio:['pipe','pipe','pipe']});let out='',err='';const timer=setTimeout(()=>{child.kill('SIGKILL');reject(Error('重编译超时'));},20000);child.on('error',e=>{clearTimeout(timer);reject(e);});child.stdout.on('data',x=>{out+=x;if(out.length>3000000){child.kill('SIGKILL');reject(Error('编译输出过大'));}});child.stderr.on('data',x=>err+=x);child.on('close',code=>{clearTimeout(timer);if(code!==0)return reject(Error(err||'编译器进程失败'));try{resolve(JSON.parse(out));}catch(e){reject(e);}});child.stdin.on('error',()=>{});child.stdin.end(JSON.stringify(input));});}
function artifacts(contracts){const out={};for(const file of Object.keys(contracts||{}).sort()){out[file]={};for(const name of Object.keys(contracts[file]).sort()){const c=contracts[file][name];if(!Array.isArray(c.abi)||typeof c.evm?.bytecode?.object!=='string'||typeof c.evm?.deployedBytecode?.object!=='string')throw Error('服务结果缺少 ABI、创建或运行字节码');out[file][name]={abi:c.abi,bytecode:c.evm.bytecode.object.replace(/^0x/,'').toLowerCase(),deployedBytecode:c.evm.deployedBytecode.object.replace(/^0x/,'').toLowerCase()};}}if(Object.keys(out).length===0)throw Error('没有编译产物');return out;}
export async function verifyMaterial(material,chainEvidence){const {id,evidence,signer,signature,signerType,...payload}=material;const base={method:'local-solc-independent-recompile',supportedVersion:SUPPORTED_VERSION,createdAt:new Date().toISOString(),providerAuthenticityVerified:false,scope:'发布材料与链上摘要、固定输入的 ABI 和完整字节码一致性；不证明提供方身份、网络历史或服务质量'};const result=(outcome,reason,extra={})=>({...base,outcome,reason,...extra});try{const digest=ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify(payload)));if(digest!==chainEvidence||evidence!==chainEvidence)return result(3,'存储材料与链上摘要不一致，原材料不可恢复，不归责发布者');if(ethers.verifyMessage(`ProofDock evidence:${digest}`,signature).toLowerCase()!==signer.toLowerCase())return result(3,'发布者签名无法验证');if(payload.demo!==false||!['remix','local-solidity'].includes(payload.service)||payload.executionStatus!=='COMPILED')return result(3,'该记录不是已完成的受支持编译，无法自动复验');const input=payload.input;if(input?.version!==SUPPORTED_VERSION||payload.version!==SUPPORTED_VERSION)return result(3,'当前仅支持固定 solc 0.8.30 完整版本');if(!input.sources||Object.keys(input.sources).length>10||JSON.stringify(input).length>150000||Object.values(input.sources).some(x=>typeof x.content!=='string'||'urls' in x))return result(3,'输入不支持：需要内嵌源码且符合大小限制');if(payload.inputHash!==hash(input)||payload.outputHash!==hash(payload.output))return result(2,'签名材料内的输入或输出哈希不符');if(payload.output?.version!==SUPPORTED_VERSION||payload.output.success!==true)return result(2,'签名材料的编译状态或版本与承诺不符');const recompiled=await localCompile(input);if(recompiled.output.errors?.some(x=>x.severity==='error'))return result(2,'同版本按原输入无法成功编译',{compilerErrors:recompiled.output.errors});let actual;try{actual=artifacts(payload.output.contracts);}catch(e){return result(3,e.message);}const expected=artifacts(recompiled.output.contracts);const expectedHash=hash(JSON.parse(canonical(expected))),observedHash=hash(JSON.parse(canonical(actual)));const equal=canonical(expected)===canonical(actual);return result(equal?1:2,equal?'原输入独立重编译：ABI、创建字节码和运行字节码全部一致':'原输入独立重编译：产物与签名记录存在差异',{expectedHash,observedHash,comparedFields:['abi','evm.bytecode.object','evm.deployedBytecode.object'],compilerVersion:recompiled.version,inputHash:hash(input)});}catch(e){return result(3,'无法验证：'+e.message);}}
