// All Remix responses in this test are mocked; no network request or payment is made.
import assert from 'node:assert/strict';import os from 'node:os';import fs from 'node:fs';import path from 'node:path';import {ethers} from 'ethers';
import {sampleRequest} from '../adapters/remix.mjs';import {PAYMENT,domain,authorizationTypes} from '../lib/payment.mjs';import {read,write} from '../lib/store.mjs';import {localCompile} from '../verification/verify.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'proofdock-remix-route-'));process.env.PROOFDOCK_DATA_DIR=dir;const {POST}=await import('../web/app/api/remix/route.js');const originalFetch=globalThis.fetch;const wallet=ethers.Wallet.createRandom();const other=ethers.Wallet.createRandom();const accepted={scheme:'exact',network:PAYMENT.network,asset:PAYMENT.asset,amount:PAYMENT.amount,payTo:PAYMENT.payTo,maxTimeoutSeconds:300,extra:{name:'USD Coin',version:'2'}};const required={x402Version:2,resource:{url:PAYMENT.resource},accepts:[accepted]};const compiled=await localCompile(sampleRequest);const body={success:true,version:sampleRequest.version,contracts:compiled.output.contracts};let calls=0,paidCalls=0,fail=false;
globalThis.fetch=async(url,options)=>{assert.equal(url,PAYMENT.resource);calls++;if(options.headers['PAYMENT-SIGNATURE']){paidCalls++;if(fail)throw Error('MOCK_NETWORK_FAILURE');return Response.json(body,{headers:{'payment-response':Buffer.from(JSON.stringify({status:'settled',network:PAYMENT.network,amount:'10000'})).toString('base64')}});}return Response.json(required,{status:402});};
const request=data=>new Request('http://localhost:4319/api/remix',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
async function payment(q){const now=Math.floor(Date.now()/1000);const authorization={from:wallet.address,to:PAYMENT.payTo,value:'10000',validAfter:String(now-600),validBefore:String(now+180),nonce:ethers.hexlify(ethers.randomBytes(32))};const signature=await wallet.signTypedData(domain,authorizationTypes,authorization);return {quoteId:q.id,paymentSignature:Buffer.from(JSON.stringify({x402Version:2,resource:required.resource,accepted:q.accepted,payload:{authorization,signature}})).toString('base64')};}
try{delete process.env.PROOFDOCK_ENABLE_REMIX_PAYMENT;assert.equal((await POST(request({paymentSignature:'test'}))).status,403);assert.equal(calls,0,'disabled payments must not forward');let r=await POST(request({input:sampleRequest}));assert.equal(r.status,200);let q=(await r.json()).quote;process.env.PROOFDOCK_ENABLE_REMIX_PAYMENT='1';const p=await payment(q);r=await POST(request(p));assert.equal(r.status,200);const execution=await r.json();assert.equal(execution.publicationPayload.demo,false);assert.equal(execution.observation.executionStatus,'COMPILED');assert.equal(read('executions',execution.executionId).owner,wallet.address);assert.equal((await POST(request(p))).status,409);assert.equal(paidCalls,1,'duplicate quote must not forward twice');let signature=await other.signMessage(`ProofDock execution\n${q.id}`);assert.equal((await POST(request({action:'result',quoteId:q.id,address:other.address,signature}))).status,401);signature=await wallet.signMessage(`ProofDock execution\n${q.id}`);r=await POST(request({action:'result',quoteId:q.id,address:wallet.address,signature}));assert.equal(r.status,200);assert.deepEqual((await r.json()).publicationPayload,execution.publicationPayload);assert.equal(paidCalls,1,'recovery must not charge again');
const recordRoute=await import('../web/app/api/route.js');const payload=execution.publicationPayload;let evidence=ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify(payload)));signature=await wallet.signMessage(`ProofDock evidence:${evidence}`);r=await recordRoute.POST(new Request('http://localhost:4319/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload,address:wallet.address,signature})}));assert.equal(r.status,200);const altered={...payload,title:'altered'};evidence=ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify(altered)));signature=await wallet.signMessage(`ProofDock evidence:${evidence}`);r=await recordRoute.POST(new Request('http://localhost:4319/api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload:altered,address:wallet.address,signature})}));assert.equal(r.status,409,'real observation cannot be fabricated or changed');
r=await POST(request({input:sampleRequest}));q=(await r.json()).quote;const p2=await payment(q);fail=true;r=await POST(request(p2));assert.equal(r.status,502);assert.equal(read('quotes',q.id).state,'uncertain');assert.equal((await POST(request(p2))).status,409);assert.equal(paidCalls,2,'uncertain payment must not retry automatically');r=await POST(new Request('http://localhost:4319/api/remix',{method:'POST',headers:{'Content-Type':'application/json',origin:'https://untrusted.example'},body:JSON.stringify({input:sampleRequest})}));assert.equal(r.status,502);
console.log('PASS: mocked x402 execution, default payment block, duplicate prevention, owner-only recovery, immutable real record, uncertain-payment protection, cross-site rejection; no real payment');}finally{globalThis.fetch=originalFetch;delete process.env.PROOFDOCK_ENABLE_REMIX_PAYMENT;fs.rmSync(dir,{recursive:true,force:true});}
