import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';import os from 'node:os';import fs from 'node:fs';import path from 'node:path';import {ethers} from 'ethers';import solc from 'solc';import ganache from 'ganache';
import {sampleRequest,hash} from '../adapters/remix.mjs';import {localCompile,verifyMaterial} from '../verification/verify.mjs';import {processChallenge} from '../verification/process.mjs';import {write,read} from '../lib/store.mjs';import {publication} from '../lib/receipt.mjs';import {PAYMENT,domain,authorizationTypes,validatePayment,validateRequirement} from '../lib/payment.mjs';
const testData=fs.mkdtempSync(path.join(os.tmpdir(),'proofdock-verify-'));process.env.PROOFDOCK_DATA_DIR=testData;
const wallet=ethers.Wallet.createRandom();const {output}=await localCompile(sampleRequest);assert(!output.errors?.some(x=>x.severity==='error'));
const fixture=publication({input:sampleRequest,output:{success:true,version:sampleRequest.version,contracts:output.contracts},createdAt:new Date().toISOString(),executionStatus:'COMPILED',inputHash:hash(sampleRequest),outputHash:hash({success:true,version:sampleRequest.version,contracts:output.contracts}),paymentResponse:null},crypto.randomUUID());
async function material(payload,signer=wallet){const evidence=ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify(payload)));return {...payload,id:ethers.id(payload.taskId),evidence,signer:signer.address,signature:await signer.signMessage(`ProofDock evidence:${evidence}`),signerType:'publisher'};}
let row=await material(fixture);assert.equal((await verifyMaterial(row,row.evidence)).outcome,1);
const bad=structuredClone(fixture);bad.taskId=crypto.randomUUID();bad.output.contracts['Counter.sol'].Counter.evm.bytecode.object='00';bad.outputHash=hash(bad.output);row=await material(bad);assert.equal((await verifyMaterial(row,row.evidence)).outcome,2);
const unsupported={...fixture,taskId:crypto.randomUUID(),version:'v0.8.29',input:{...fixture.input,version:'v0.8.29'}};row=await material(unsupported);assert.equal((await verifyMaterial(row,row.evidence)).outcome,3);
row=await material({...fixture,demo:true});assert.equal((await verifyMaterial(row,row.evidence)).outcome,3);
row=await material(fixture);assert.equal((await verifyMaterial({...row,input:{fake:true}},row.evidence)).outcome,3);
const required={x402Version:2,resource:{url:PAYMENT.resource},accepts:[{...PAYMENT,scheme:'exact',extra:{name:'USD Coin',version:'2'},maxTimeoutSeconds:300}]};delete required.accepts[0].resource;const accepted=validateRequirement(required);const now=Math.floor(Date.now()/1000),authorization={from:wallet.address,to:PAYMENT.payTo,value:'10000',validAfter:String(now-600),validBefore:String(now+180),nonce:ethers.hexlify(ethers.randomBytes(32))};const signature=await wallet.signTypedData(domain,authorizationTypes,authorization);const encode=x=>Buffer.from(JSON.stringify(x)).toString('base64');const payment={x402Version:2,resource:required.resource,accepted,payload:{authorization,signature}};assert.equal(validatePayment(encode(payment),{required}).owner,wallet.address);assert.throws(()=>validatePayment(encode({...payment,payload:{authorization:{...authorization,value:'20000'},signature}}),{required}));assert.throws(()=>validateRequirement({...required,accepts:[{...accepted,payTo:wallet.address}]}));
console.log('PASS：独立编译一致、字节码篡改、版本不支持、演示记录、存储损坏，以及付款签名金额/收款人校验（全部本地样本，无真实付款）');
const server=ganache.server({chain:{chainId:31337,hardfork:'shanghai'},wallet:{deterministic:true,totalAccounts:5},logging:{quiet:true}});await server.listen(0,'127.0.0.1');const rpc='http://127.0.0.1:'+server.address().port;const provider=new ethers.JsonRpcProvider(rpc,undefined,{cacheTimeout:-1});provider.pollingInterval=50;
try{const admin=await provider.getSigner(0),publisher=await provider.getSigner(1),challenger=await provider.getSigner(2),validator=await provider.getSigner(3);const publisherWallet=ethers.HDNodeWallet.fromPhrase('myth like bonus scare over problem client lizard pioneer submit female collect',undefined,"m/44'/60'/0'/0/1");const buildInput={language:'Solidity',sources:{'ProofDock.sol':{content:fs.readFileSync('contracts/ProofDock.sol','utf8')}},settings:{evmVersion:'shanghai',outputSelection:{'*':{'*':['abi','evm.bytecode']}}}};const compiled=JSON.parse(solc.compile(JSON.stringify(buildInput),{import:n=>({contents:fs.readFileSync(path.join('node_modules',n),'utf8')})}));const deploy=async(name,args)=>{const c=compiled.contracts['ProofDock.sol'][name];const contract=await new ethers.ContractFactory(c.abi,c.evm.bytecode.object,admin).deploy(...args);await contract.waitForDeployment();return contract;};const token=await deploy('DemoCredit',[]);const dock=await deploy('ProofDock',[await token.getAddress(),await validator.getAddress()]);const cfg={rpc,dock:await dock.getAddress(),dockAbi:compiled.contracts['ProofDock.sol'].ProofDock.abi};for(const s of [publisher,challenger]){await(await token.transfer(await s.getAddress(),ethers.parseEther('100'))).wait();await(await token.connect(s).approve(cfg.dock,ethers.parseEther('100'))).wait();}
for(const [payload,outcome,state] of [[fixture,1,3],[bad,2,4],[unsupported,3,1]]){const m=await material({...payload,taskId:crypto.randomUUID()},publisherWallet);write('records',m.id,m);await(await dock.connect(publisher).publish(m.id,m.evidence)).wait();assert.equal(await processChallenge({cfg,provider,material:m}),null,'未挑战不能自动裁定');const publisherBefore=await dock.credits(await publisher.getAddress()),challengerBefore=await dock.credits(await challenger.getAddress());await(await dock.connect(challenger).challenge(m.id,ethers.id('TEST_CHALLENGE'))).wait();const job=await processChallenge({cfg,provider,material:m});assert.equal(job.report.outcome,outcome);assert.equal(job.status,'resolved');assert.equal(Number((await dock.records(m.id)).state),state);assert.equal(job.reportHash,ethers.keccak256(ethers.toUtf8Bytes(JSON.stringify(job.report))));assert((await provider.getTransactionReceipt(job.txHash)).status===1);assert.equal(read('reports',job.id).reportHash,job.reportHash);if(outcome===1)assert.equal(await dock.credits(await publisher.getAddress())-publisherBefore,ethers.parseEther('5'));if(outcome===2)assert.equal(await dock.credits(await challenger.getAddress())-challengerBefore,ethers.parseEther('15'));if(outcome===3)assert.equal(await dock.credits(await challenger.getAddress())-challengerBefore,ethers.parseEther('5'));assert.equal(await processChallenge({cfg,provider,material:m}),null,'已裁定不能重复支付或裁定');}
fs.writeFileSync(path.join(testData,'deployment.json'),JSON.stringify(cfg));const autoRow=await material({...fixture,taskId:crypto.randomUUID()},publisherWallet);write('records',autoRow.id,autoRow);await(await dock.connect(publisher).publish(autoRow.id,autoRow.evidence)).wait();const worker=spawn(process.execPath,['scripts/validator.mjs'],{env:{...process.env,PROOFDOCK_DATA_DIR:testData},stdio:['ignore','pipe','pipe']});let workerLog='';worker.stdout.on('data',x=>workerLog+=x);worker.stderr.on('data',x=>workerLog+=x);try{for(let round=0;round<2;round++){await(await dock.connect(challenger).challenge(autoRow.id,ethers.id('SAME_REASON'))).wait();const deadline=Date.now()+25000;while(Number((await dock.records(autoRow.id)).state)===2&&Date.now()<deadline)await new Promise(r=>setTimeout(r,200));assert.equal(Number((await dock.records(autoRow.id)).state),3,workerLog);}const jobs=(await import('../lib/store.mjs')).all('reports').filter(x=>x.recordId===autoRow.id);assert.equal(jobs.length,2,'repeat challenges get independent reports');assert.notEqual(jobs[0].id,jobs[1].id);const orphan=ethers.id('orphan-material');await(await dock.connect(publisher).publish(orphan,ethers.id('missing-evidence'))).wait();await(await dock.connect(challenger).challenge(orphan,ethers.id('missing'))).wait();const deadline=Date.now()+10000;while(Number((await dock.records(orphan)).state)===2&&Date.now()<deadline)await new Promise(r=>setTimeout(r,200));assert.equal(Number((await dock.records(orphan)).state),1,'missing material cannot verify');console.log('PASS: background worker, repeated challenges, missing material refund');}finally{worker.kill('SIGTERM');await new Promise(resolve=>{if(worker.exitCode!==null)return resolve();worker.once('exit',resolve);});}
console.log('PASS：隔离测试链发布→挑战→自动重编译→报告哈希上链→三种裁定资金分配；未修改用户当前测试链');}finally{provider.destroy();await server.close();fs.rmSync(testData,{recursive:true,force:true});}
