import {ethers} from 'ethers';
import {config,all,trustedOrigin} from '../../../../../lib/store.mjs';
import {readDetail} from '../../detail.js';
export const dynamic='force-dynamic';
const services=[{id:'local-solidity',name:'本地 Solidity 编译',category:'solidity-compilation',executionStatus:'local-demo-available',executionEndpoint:'/api/local-compiler'},{id:'remix',name:'Remix',category:'solidity-compilation',executionStatus:'payment-disabled',executionEndpoint:'/api/remix'},{id:'onecompiler',name:'OneCompiler',category:'solidity-compilation',executionStatus:'not-integrated',executionEndpoint:null}];
const states=['unpublished','published','challenged','verified','invalidated','exited'];
class ApiError extends Error{constructor(status,code,message){super(message);Object.assign(this,{status,code});}}
const fail=(status,code,message)=>{throw new ApiError(status,code,message);};
function response(data,status=200){return Response.json({apiVersion:'1',...data},{status,headers:{'Cache-Control':'no-store'}});}
function bytes32(value,name){if(!ethers.isHexString(value,32))fail(400,'INVALID_PARAMETER',`${name} 必须是 bytes32`);return value;}
function address(value){if(!ethers.isAddress(value))fail(400,'INVALID_PARAMETER','address 必须是钱包地址');return ethers.getAddress(value);}
async function withChain(fn){const cfg=config(),provider=new ethers.JsonRpcProvider(cfg.rpc,undefined,{cacheTimeout:-1});try{if(Number((await provider.getNetwork()).chainId)!==cfg.chainId)fail(503,'CHAIN_MISMATCH','RPC 网络不匹配');return await fn(cfg,new ethers.Contract(cfg.dock,cfg.dockAbi,provider));}finally{provider.destroy();}}
function summary(row,rec){return {id:row.id,title:row.title,serviceId:row.service,version:row.version??null,evidenceHash:row.evidence,publisher:rec.publisher,state:Number(rec.state),status:states[Number(rec.state)],queryAvailable:[1,3].includes(Number(rec.state)),exitAt:Number(rec.exitAt),challengedAt:Number(rec.challengedAt),demo:row.demo===true};}
async function record(chain,id){const row=all('records').find(x=>x.id===id);if(!row)fail(404,'RECORD_NOT_FOUND','记录不存在');const rec=await chain.records(id);if(Number(rec.state)===0)fail(404,'RECORD_NOT_PUBLISHED','记录尚未发布上链');if(rec.evidence!==row.evidence||rec.publisher.toLowerCase()!==row.signer.toLowerCase())fail(409,'EVIDENCE_MISMATCH','材料与链上记录不符');return {row,rec};}
async function dispatch(req){const u=new URL(req.url),parts=u.pathname.replace(/^\/api\/v1\/?/,'').split('/').filter(Boolean);
if(req.method==='GET'&&parts.join('/')==='services'){const q=(u.searchParams.get('q')||'').toLowerCase();return response({services:services.filter(s=>`${s.id} ${s.name} ${s.category}`.toLowerCase().includes(q))});}
if(req.method==='GET'&&parts.join('/')==='records'){const limit=Number(u.searchParams.get('limit')||20),offset=Number(u.searchParams.get('offset')||0),service=u.searchParams.get('serviceId'),state=u.searchParams.get('status');if(!Number.isInteger(limit)||limit<1||limit>100||!Number.isInteger(offset)||offset<0)fail(400,'INVALID_PARAMETER','limit 为 1–100，offset 为非负整数');if(service&&!services.some(s=>s.id===service))fail(400,'INVALID_PARAMETER','未知 serviceId');if(state&&!states.includes(state))fail(400,'INVALID_PARAMETER','未知 status');return withChain(async(cfg,chain)=>{const rows=all('records').filter(r=>!service||r.service===service);const list=[];for(const row of rows){const rec=await chain.records(row.id);if(Number(rec.state)>0&&rec.evidence===row.evidence&&rec.publisher.toLowerCase()===row.signer.toLowerCase()){const item=summary(row,rec);if(!state||item.status===state)list.push(item);}}list.sort((a,b)=>a.id.localeCompare(b.id));return response({records:list.slice(offset,offset+limit),pagination:{offset,limit,total:list.length,nextOffset:offset+limit<list.length?offset+limit:null}});});}
if(parts[0]==='records'&&parts[1]){const id=bytes32(parts[1],'recordId');
if(req.method==='GET'&&parts.length===2)return withChain(async(cfg,chain)=>{const {row,rec}=await record(chain,id);const reports=all('reports').filter(r=>r.recordId===id&&r.status==='resolved');return response({record:summary(row,rec),verification:reports.map(r=>({outcome:r.report.outcome,reason:r.report.reason,method:r.report.method,transactionHash:r.txHash,reportHash:r.reportHash})),verificationScope:'仅证明该记录的复验结果，不保证服务当前在线或未来履约'});});
if(req.method==='GET'&&parts[2]==='quote'&&parts.length===3){const buyer=address(u.searchParams.get('address'));return withChain(async(cfg,chain)=>{const {row,rec}=await record(chain,id);const events=await chain.queryFilter(chain.filters.Queried(null,id,buyer),0,'latest');const prior=events.at(-1);const fee=await chain.FEE();const queryId=prior?.args.queryId||ethers.hexlify(ethers.randomBytes(32));const expiresAt=Math.floor(Date.now()/1000)+300;const message=`ProofDock read v1\n${cfg.chainId}\n${cfg.dock}\n${id}\n${queryId}\n${buyer}\n${expiresAt}`;if(!prior&&![1,3].includes(Number(rec.state)))fail(409,'RECORD_UNAVAILABLE','当前状态不能购买查询');return response({record:summary(row,rec),access:{paymentRequired:!prior,queryId,existingPaymentTransaction:prior?.transactionHash||null},payment:{chainId:cfg.chainId,rpc:cfg.rpc,token:cfg.token,symbol:'DCR',amount:ethers.formatEther(fee),amountBaseUnits:fee.toString(),gasPayer:buyer,transactions:prior?[]:[{purpose:'approve-if-allowance-insufficient',to:cfg.token,data:new ethers.Interface(cfg.tokenAbi).encodeFunctionData('approve',[cfg.dock,fee]),value:'0'},{purpose:'pay-query',to:cfg.dock,data:chain.interface.encodeFunctionData('query',[id,queryId]),value:'0'}]},readAuthorization:{address:buyer,expiresAt,message,endpoint:`/api/v1/records/${id}/evidence`,method:'POST',bodyFields:['address','queryId','expiresAt','signature']}});});}
if(req.method==='POST'&&parts[2]==='evidence'&&parts.length===3){trustedOrigin(req);if(Number(req.headers.get('content-length')||0)>8192)fail(413,'BODY_TOO_LARGE','请求过大');const raw=await req.text();if(raw.length>8192)fail(413,'BODY_TOO_LARGE','请求过大');let body;try{body=JSON.parse(raw);}catch{fail(400,'INVALID_JSON','请求必须是 JSON');}const buyer=address(body.address),q=bytes32(body.queryId,'queryId'),expiresAt=body.expiresAt,now=Math.floor(Date.now()/1000);if(!Number.isInteger(expiresAt)||expiresAt<=now||expiresAt>now+300)fail(401,'AUTHORIZATION_EXPIRED','读取授权已过期或有效期超过五分钟');if(typeof body.signature!=='string')fail(401,'INVALID_SIGNATURE','缺少签名');const cfg=config(),message=`ProofDock read v1\n${cfg.chainId}\n${cfg.dock}\n${id}\n${q}\n${buyer}\n${expiresAt}`;let recovered;try{recovered=ethers.verifyMessage(message,body.signature);}catch{fail(401,'INVALID_SIGNATURE','签名无效');}if(recovered.toLowerCase()!==buyer.toLowerCase())fail(401,'INVALID_SIGNATURE','签名地址不符');const legacyUrl=new URL('/api',u.origin);for(const [key,value] of Object.entries({id,queryId:q,address:buyer,signature:body.signature}))legacyUrl.searchParams.set(key,value);const res=await readDetail(new Request(legacyUrl),cfg,{signatureMessage:message});const evidence=await res.json();if(!res.ok)fail(res.status,res.status===402?'PAYMENT_REQUIRED':res.status===409?'EVIDENCE_MISMATCH':'READ_FAILED',evidence.error);const result=response({recordId:id,queryId:q,evidence});result.headers.set('Server-Timing',res.headers.get('Server-Timing')||'');return result;}
}
fail(404,'ENDPOINT_NOT_FOUND','接口不存在');}
async function handle(req){try{return await dispatch(req);}catch(e){console.error('Agent API:',e.code||e.message);return response({error:{code:e.code||'SERVICE_UNAVAILABLE',message:e.status?e.message:'服务暂不可用，请稍后重试',retryable:!e.status||e.status>=500}},e.status||503);}}
export const GET=handle;export const POST=handle;
