import {ethers} from 'ethers';
import {randomUUID} from 'node:crypto';
import {info,compile,sampleRequest} from '../../../../adapters/remix.mjs';
import {read,write,claimQuote,trustedOrigin} from '../../../../lib/store.mjs';
import {validateRequirement,validatePayment} from '../../../../lib/payment.mjs';
import {publication} from '../../../../lib/receipt.mjs';
export const dynamic='force-dynamic';
export async function GET(){try{return Response.json({info:await info(),sampleRequest,paymentEnabled:process.env.PROOFDOCK_ENABLE_REMIX_PAYMENT==='1'});}catch(e){return Response.json({error:e.message},{status:502});}}
export async function POST(req){try{trustedOrigin(req);const {input,paymentSignature,quoteId,action,address,signature}=await req.json();if(action==='result'){const q=read('quotes',quoteId);const execution=q?.executionId?read('executions',q.executionId):null;if(!execution)return Response.json({error:'当前没有可恢复的执行结果；付款状态可能不确定，请勿重复付款',state:q?.state||'unknown'},{status:409});if(!address||!signature||ethers.verifyMessage(`ProofDock execution\n${quoteId}`,signature).toLowerCase()!==execution.owner.toLowerCase()||address.toLowerCase()!==execution.owner.toLowerCase())return Response.json({error:'需要原付款钱包的读取签名'},{status:401});return Response.json({executionId:execution.id,observation:execution.observation,publicationPayload:publication(execution.observation,execution.id)});}if(paymentSignature){if(process.env.PROOFDOCK_ENABLE_REMIX_PAYMENT!=='1')return Response.json({error:'真实付款暂未启用；当前设置遵循“暂不付款”。'},{status:403});const q=read('quotes',quoteId);if(!q||q.expiresAt<Date.now()||q.state!=='quoted')return Response.json({error:'报价已过期或已提交，请勿重复付款'},{status:409});const {owner}=validatePayment(paymentSignature,q);if(!claimQuote(quoteId))return Response.json({error:'重复提交'},{status:409});let observation;try{observation=await compile(q.input,paymentSignature);}catch(e){write('quotes',quoteId,{...q,state:'uncertain',error:'请求失败，支付可能已结算。请勿自动重试。'});throw Error('请求失败，支付可能已结算，请勿重复付款：'+e.message);}const executionId=randomUUID();write('executions',executionId,{id:executionId,owner,observation});write('quotes',quoteId,{...q,state:'completed',executionId});return Response.json({observation,executionId,publicationPayload:publication(observation,executionId)});}
const observation=await compile(input||sampleRequest);let quote=null;if(observation.httpStatus===402){const accepted=validateRequirement(observation.paymentRequired);const id=randomUUID();const q={id,input:observation.input,required:observation.paymentRequired,accepted,expiresAt:Date.now()+180000,state:'quoted'};write('quotes',id,q);quote={id,required:q.required,accepted,expiresAt:q.expiresAt};}return Response.json({observation,quote},{status:observation.httpStatus===402?200:observation.httpStatus});}catch(e){return Response.json({error:e.message},{status:502});}}
