import {readDetail} from './detail.js';
import {read as readStore,trustedOrigin} from '../../../lib/store.mjs';
import {publication} from '../../../lib/receipt.mjs';
import fs from 'node:fs';import path from 'node:path';import {ethers} from 'ethers';import {createRequire} from 'node:module';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite');
const store=()=>{const db=new DatabaseSync(path.join(root(),'proofdock.sqlite'));db.exec('CREATE TABLE IF NOT EXISTS records (id TEXT PRIMARY KEY, payload TEXT NOT NULL)');return db;};
export const dynamic='force-dynamic';
const root=()=>path.join(process.cwd(),process.cwd().endsWith('/web')?'../data':'data');
const config=()=>JSON.parse(fs.readFileSync(path.join(root(),'deployment.json'),'utf8'));
const database=()=>{const db=store();try{return db.prepare('SELECT payload FROM records').all().map(r=>JSON.parse(r.payload));}finally{db.close();}};
export async function GET(req){try{const u=new URL(req.url),action=u.searchParams.get('action');if(action==='services')return Response.json([{id:'local-solidity',name:'本地 Solidity 编译',status:'running_local_demo',endpoint:'/api/local-compiler'},{id:'remix',name:'Remix',status:'payment_ready',execution:'disabled_by_default',probeEndpoint:'/api/remix'},{id:'onecompiler',name:'OneCompiler',status:'接口预留'}]);if(action==='execute'||action==='verify')return Response.json({error:'not_implemented',message:'真实服务与复验尚未接入'},{status:501});const cfg=config();if(action==='detail')return readDetail(req,cfg);const chain=new ethers.Contract(cfg.dock,cfg.dockAbi,new ethers.JsonRpcProvider(cfg.rpc));
const rows=await Promise.all(database().map(async x=>{const r=await chain.records(x.id);return {id:x.id,title:x.title,service:x.service,evidence:x.evidence,publisher:r.publisher,state:r.evidence===x.evidence&&r.publisher.toLowerCase()===x.signer.toLowerCase()?Number(r.state):0,exitAt:Number(r.exitAt),challengedAt:Number(r.challengedAt)};}));return Response.json(rows.filter(x=>x.state>0));}catch(e){return Response.json({error:e.message},{status:503})}}
export async function POST(req){try{trustedOrigin(req);const {payload,address,signature}=await req.json();if(payload?.demo!==true){const execution=readStore('executions',payload.executionId);if(!execution||execution.owner.toLowerCase()!==address.toLowerCase()||JSON.stringify(publication(execution.observation,execution.id))!==JSON.stringify(payload))return Response.json({error:'真实记录必须来自该钱包实际执行的原始服务响应，不能自行修改'},{status:409});}const encoded=JSON.stringify(payload),evidence=ethers.keccak256(ethers.toUtf8Bytes(encoded));if(ethers.verifyMessage(`ProofDock evidence:${evidence}`,signature).toLowerCase()!==address.toLowerCase())return Response.json({error:'签名不符'},{status:401});if(encoded.length>200000||!payload.title||!['remix','onecompiler','local-solidity'].includes(payload.service)||!payload.taskId)return Response.json({error:'材料不完整'},{status:400});const id=ethers.keccak256(ethers.toUtf8Bytes(payload.taskId));const rows=database();const previous=rows.find(x=>x.id===id);if(previous){if(previous.evidence===evidence&&previous.signer.toLowerCase()===address.toLowerCase())return Response.json({id,evidence});return Response.json({error:'重复任务'},{status:409});}const db=store();try{db.prepare('INSERT INTO records(id,payload) VALUES(?,?)').run(id,JSON.stringify({...payload,id,evidence,signer:address,signature,signerType:payload.demo===false?'publisher':'publisher-demo'}));}finally{db.close();}return Response.json({id,evidence});}catch(e){return Response.json({error:e.message},{status:400})}}
